import { PDFDocument, rgb } from '/node_modules/pdf-lib/dist/pdf-lib.esm.js';
import * as pdfjsLib from '/node_modules/pdfjs-dist/legacy/build/pdf.mjs';
pdfjsLib.GlobalWorkerOptions.workerSrc='/node_modules/pdfjs-dist/legacy/build/pdf.worker.mjs';
const $=s=>document.querySelector(s), pick=$('#pick'), drop=$('#drop'), controls=$('#controls'), make=$('#make'), download=$('#download'), status=$('#status'), nameEl=$('#name'), detectedSize=$('#detected-size'), outputPreview=$('#output-preview'), scaleToggle=$('#scale-to-fit'), fitInfo=$('#fit-info');
let file=null,source=null,outputUrl=null;
const setStatus=(t,k='')=>{status.textContent=t;status.className=k};
const clearOutput=()=>{if(outputUrl)URL.revokeObjectURL(outputUrl);outputUrl=null;download.disabled=true;outputPreview.hidden=true};
const open=()=>pick.click();
function pageSize(index,slot=1){const mode=$(`#p${slot}-size`)?.value||'pdf',standard={a4p:[595.28,841.89],a4l:[841.89,595.28],letterp:[612,792],letterl:[792,612]};if(standard[mode])return{width:standard[mode][0],height:standard[mode][1]};const p=source.getPage(index),s=p.getCropBox(),a=((p.getRotation().angle%360)+360)%360;return a===90||a===270?{width:s.height,height:s.width}:{width:s.width,height:s.height}}
function values(slot){const v=Object.fromEntries(['left','top','right','bottom'].map(k=>[k,Math.max(0,Math.min(99,Number($(`#p${slot}-${k}`).value)||0))]));for(const [a,b] of [['left','right'],['top','bottom']])if(v[a]+v[b]>=100){const ratio=99.9/(v[a]+v[b]);v[a]*=ratio;v[b]*=ratio}return v}
function updateSelection(slot){const v=values(slot),el=$(`#preview${slot} .selection`);for(const k of ['left','top','right','bottom'])el.style[k]=`${v[k]}%`;updateFitInfo()}
function setValues(slot,x,y,w,h){const set=(key,val)=>{$(`#p${slot}-${key}`).value=Math.max(0,Math.min(99,val)).toFixed(1).replace('.0','')};set('left',x*100);set('top',y*100);set('right',(1-x-w)*100);set('bottom',(1-y-h)*100);settingsChanged();updateSelection(slot)}
async function renderPreview(slot,index){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,page=await pdf.getPage(index+1),viewport=page.getViewport({scale:1.2}),preview=$(`#preview${slot}`),canvas=preview.querySelector('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;preview.style.aspectRatio=`${viewport.width}/${viewport.height}`;updateSelection(slot)}
function bindCrop(slot){const preview=$(`#preview${slot}`);let start=null;preview.addEventListener('pointerdown',e=>{const r=preview.getBoundingClientRect();start={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};preview.setPointerCapture(e.pointerId)});preview.addEventListener('pointermove',e=>{if(!start)return;const r=preview.getBoundingClientRect(),ex=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),ey=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));setValues(slot,Math.min(start.x,ex),Math.min(start.y,ey),Math.abs(ex-start.x),Math.abs(ey-start.y))});preview.addEventListener('pointerup',()=>{start=null});preview.addEventListener('pointercancel',()=>{start=null});['left','top','right','bottom'].forEach(k=>$(`#p${slot}-${k}`).addEventListener('input',()=>updateSelection(slot)))}
function clearLoadedFile(){file=null;source=null;clearOutput();controls.hidden=true;drop.hidden=false;make.disabled=true}
async function accept(f){clearOutput();file=null;source=null;scaleToggle.checked=false;$('#p1-size').value='pdf';$('#p2-size').value='pdf';make.disabled=true;setStatus('');try{if(!f||(!f.type.includes('pdf')&&!f.name.toLowerCase().endsWith('.pdf')))throw new Error('Choose a PDF file.');const data=await f.arrayBuffer(),loaded=await PDFDocument.load(data);if(loaded.getPageCount()<2)throw new Error('This PDF needs at least two pages.');file=f;source=loaded;$('#filename').textContent=f.name;$('#page-count').textContent=`${source.getPageCount()} pages`;const detected=pageSize(0),detectedName=Math.abs(detected.width-612)<2&&Math.abs(detected.height-792)<2?'US Letter-like':Math.abs(detected.width-595.28)<2&&Math.abs(detected.height-841.89)<2?'A4-like':'custom';detectedSize.textContent=`Detected: ${detected.width.toFixed(1)} × ${detected.height.toFixed(1)} pt (${detectedName})`;document.querySelectorAll('#page1,#page2').forEach((select,index)=>{select.replaceChildren(...source.getPageIndices().map(i=>{const o=document.createElement('option');o.value=i;o.textContent=`Page ${i+1}`;return o}));select.value=String(index)});drop.hidden=true;controls.hidden=false;make.disabled=false;await renderPreview(1,0);await renderPreview(2,1);updateFitInfo()}catch(e){clearLoadedFile();setStatus(e.message||'Could not read this PDF. Choose a valid PDF with at least two pages.','error')}}
function cropPhysical(slot,index){const s=pageSize(index,slot),v=values(slot);return{width:s.width*(1-v.left/100-v.right/100),height:s.height*(1-v.top/100-v.bottom/100)}}
function outputGeometry(){const a=Number($('#page1').value),b=Number($('#page2').value),p=$('#paper').value,one=cropPhysical(1,a),two=cropPhysical(2,b),s1=pageSize(a,1),W=p==='auto'?s1.width:p==='a4'?595.28:612,H=p==='auto'?s1.height:p==='a4'?841.89:792,horizontal=$('#orientation').value==='horizontal',gap=18,margin=24,slotW=horizontal?(W-gap-2*margin)/2:W-2*margin,slotH=horizontal?H-2*margin:(H-gap-2*margin)/2;return{one,two,W,H,horizontal,gap,margin,slotW,slotH}}
function updateFitInfo(){if(!source||!controls||controls.hidden)return;try{const g=outputGeometry(),factors=[Math.min(1,g.slotW/g.one.width,g.slotH/g.one.height),Math.min(1,g.slotW/g.two.width,g.slotH/g.two.height)],bad=factors.some(x=>x<1-1e-8),fmt=(w,h)=>`${(w/72).toFixed(2)} × ${(h/72).toFixed(2)} in (${(w*25.4/72).toFixed(1)} × ${(h*25.4/72).toFixed(1)} mm)`,details=`Crop 1: ${fmt(g.one.width,g.one.height)}; crop 2: ${fmt(g.two.width,g.two.height)}. Each assigned slot: ${fmt(g.slotW,g.slotH)}. Layout spacing: 0.33 in (24 pt) outer margins and 0.25 in (18 pt) gap.`;fitInfo.textContent=bad?(scaleToggle.checked?`Crops will be scaled down to ${factors.map(x=>`${(x*100).toFixed(1)}%`).join(' and ')} of true size. ${details}`:`One or both crops exceed their assigned slot at true size. ${details} Change the crop, paper size, or layout, or opt in to automatic scaling.`):`Both crops fit at true physical size. ${details}`;fitInfo.className=bad&&!scaleToggle.checked?'error':'';make.disabled=Number($('#page1').value)===Number($('#page2').value)}catch{}}
function updateSelectors(){const same=$('#page1').value===$('#page2').value;$('#page1').setCustomValidity(same?'Choose different source pages.':'');$('#page2').setCustomValidity(same?'Choose different source pages.':'');updateFitInfo()}
function settingsChanged(){clearOutput();setStatus('');updateFitInfo()}
download.onclick=()=>{if(!outputUrl)return;const a=document.createElement('a');a.href=outputUrl;let n=nameEl.value.trim()||'two-pages-one';n=n.replace(/\.pdf$/i,'');a.download=`${n}.pdf`;document.body.append(a);a.click();a.remove()};drop.onclick=open;$('#change').onclick=()=>{pick.value='';open()};pick.onchange=()=>pick.files[0]&&accept(pick.files[0]);drop.ondragover=e=>{e.preventDefault();drop.classList.add('active')};drop.ondragleave=()=>drop.classList.remove('active');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('active');accept(e.dataTransfer.files[0])};$('#page1').onchange=()=>{updateSelectors();renderPreview(1,Number($('#page1').value)).catch(e=>setStatus(e.message,'error'))};$('#page2').onchange=()=>{updateSelectors();renderPreview(2,Number($('#page2').value)).catch(e=>setStatus(e.message,'error'))};controls.addEventListener('input',settingsChanged);controls.addEventListener('change',settingsChanged);bindCrop(1);bindCrop(2);
async function renderOutputPreview(bytes){const output=await pdfjsLib.getDocument({data:bytes.slice()}).promise,page=await output.getPage(1),viewport=page.getViewport({scale:1.05}),canvas=outputPreview.querySelector('canvas');canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;outputPreview.hidden=false}
async function renderCrop(slot,index){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,page=await pdf.getPage(index+1),viewport=page.getViewport({scale:2}),full=document.createElement('canvas');full.width=Math.ceil(viewport.width);full.height=Math.ceil(viewport.height);await page.render({canvasContext:full.getContext('2d'),viewport}).promise;const size=pageSize(index,slot),v=values(slot),sx=Math.round(full.width*v.left/100),sy=Math.round(full.height*v.top/100),sw=Math.max(1,Math.round(full.width*(1-v.left/100-v.right/100))),sh=Math.max(1,Math.round(full.height*(1-v.top/100-v.bottom/100))),cropped=document.createElement('canvas');cropped.width=sw;cropped.height=sh;cropped.getContext('2d').drawImage(full,sx,sy,sw,sh,0,0,sw,sh);return{data:cropped.toDataURL('image/png'),width:size.width*sw/full.width,height:size.height*sh/full.height}}
make.onclick=async()=>{if(!source)return;clearOutput();make.disabled=true;make.textContent='Building locally…';try{const a=Number($('#page1').value),b=Number($('#page2').value);if(a===b)throw new Error('Choose two different source pages.');const g=outputGeometry(),factors=[Math.min(1,g.slotW/g.one.width,g.slotH/g.one.height),Math.min(1,g.slotW/g.two.width,g.slotH/g.two.height)];if(factors.some(x=>x<1-1e-8)&&!scaleToggle.checked){const fmt=x=>`${(x/72).toFixed(2)} in (${(x*25.4/72).toFixed(1)} mm)`,overflow=[g.one,g.two].flatMap((crop,i)=>{const dims=[];if(crop.width>g.slotW+1e-6)dims.push(`width ${fmt(crop.width)} exceeds ${fmt(g.slotW)}`);if(crop.height>g.slotH+1e-6)dims.push(`height ${fmt(crop.height)} exceeds ${fmt(g.slotH)}`);return dims.map(d=>`Crop ${i+1} ${d}`)});throw new Error(`${overflow.join('; ')}. Change the crop, paper size, or layout, or enable “Automatically scale crops to fit.”`)}const one=await renderCrop(1,a),two=await renderCrop(2,b),out=await PDFDocument.create(),imgs=[await out.embedPng(one.data),await out.embedPng(two.data)],infos=[one,two],page=out.addPage([g.W,g.H]);page.drawRectangle({x:0,y:0,width:g.W,height:g.H,color:rgb(1,1,1)});infos.forEach((info,i)=>{const scale=factors[i],w=info.width*scale,h=info.height*scale,x=g.horizontal?g.margin+i*(g.slotW+g.gap)+(g.slotW-w)/2:g.margin+(g.slotW-w)/2,y=g.horizontal?g.margin+(g.slotH-h)/2:g.margin+(i?0:g.slotH+g.gap)+(g.slotH-h)/2;page.drawImage(imgs[i],{x,y,width:w,height:h})});const bytes=await out.save();await renderOutputPreview(bytes);outputUrl=URL.createObjectURL(new Blob([bytes],{type:'application/pdf'}));download.disabled=false;setStatus(`Created one page at ${g.W.toFixed(1)} × ${g.H.toFixed(1)} pt. Crops are rasterized${factors.some(x=>x<1-1e-8)?`; scaled to ${(factors[0]*100).toFixed(1)}% and ${(factors[1]*100).toFixed(1)}%`: ' at true physical size'}.`,'success')}catch(e){console.error(e);clearOutput();setStatus(e.message||'Could not build this PDF.','error')}finally{make.textContent='Build PDF →';make.disabled=!source||source.getPageCount()<2||$('#page1').value===$('#page2').value}};
